# Generated by Django 3.2.4 on 2021-06-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
        ('helprequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medic.medic'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='medic_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='patient_location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='patient_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='time_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='time_concluded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
