# Generated by Django 3.2.4 on 2021-07-07 03:48

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helprequest', '0002_auto_20210625_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='patient', unique_with=('id',)),
            preserve_default=False,
        ),
    ]
