# Generated by Django 3.2.4 on 2021-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helprequest', '0002_auto_20210625_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='time_accepted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
