# Generated by Django 3.2.4 on 2021-06-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_helprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
