# Generated by Django 3.2.4 on 2021-06-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medic',
            old_name='Speciality',
            new_name='speciality',
        ),
    ]
