# Generated by Django 3.2.4 on 2021-06-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0002_rename_speciality_medic_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='country',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='medic',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='medic',
            name='speciality',
            field=models.CharField(max_length=120),
        ),
    ]
