# Generated by Django 3.2.4 on 2021-06-07 11:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medic', '0003_auto_20210607_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medic',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='medic',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='medic',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='name',
        ),
        migrations.AddField(
            model_name='medic',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medic',
            name='medic_id',
            field=models.CharField(max_length=120),
        ),
    ]
